version: '3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_anvari
    ports:
      - ${POSTGRES_HOST_PORT:-24000}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/backup:/backup
      - ./data/archive:/archive
      - ./database:/code
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-random_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-random_user}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA:-random_user}
    profiles:
      - db
      - default
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_anvari
    ports:
      - ${ZOOKEEPER_HOST_PORT:-2181}:2181
    restart: unless-stopped
    profiles:
      - default

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_anvari
    ports:
      - ${KAFKA_HOST_PORT:-9092}:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "${KAFKA_TOPICS}:-add_ts:1:1,add_info:1:1,add_to_db:1:1"
    restart: unless-stopped
    depends_on:
      - zookeeper
    profiles:
      - default

  nocodb: 
    image: "nocodb/nocodb:0.204.4"
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"
      NC_JWT_EXPIRES_IN: ${NC_JWT_EXPIRES_IN:-48h}
      NC_ADMIN_EMAIL: ${NC_ADMIN_EMAIL:-ama@gmail.com}
      NC_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD:-12345678}
    ports: 
      - "${NOCODB_HOST_PORT:-8080}:8080"
    restart: always
    volumes:
      - "./data/nc_data:/usr/app/data"
    profiles:
      - default
      - nocodb

  root_db: 
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    ports:
      - "24005:5432"
    restart: always
    volumes:
      - "./data/db_data:/var/lib/postgresql/data"
    profiles:
      - default
      - nocodb
